[pytest]
minversion = 2.0
norecursedirs = .git .tox requirements*
python_files = test*.py
testpaths = tests sim2l/tests
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning:traitlets
    ignore::DeprecationWarning:ansiwrap
