#!/usr/bin/env python3
# @package    sim2l library
# @copyright  Copyright (c) 2005-2026 Purdue University.
# @license    http://opensource.org/licenses/MIT MIT

"""
Example: Using FileManager to manage sim2l generated files.

This example demonstrates how to:
1. Get files from a specific sim2l run
2. Get all files for a simulation across multiple runs
3. Export files to the filesystem
4. Organize files in folders
"""

from sim2l.database import FileManager, RunDatabase, get_session_manager


def example_1_get_run_files():
    """Get all files generated by a specific execution."""
    print("=" * 60)
    print("Example 1: Get files from a specific run")
    print("=" * 60)

    # Initialize file manager (local mode)
    fm = FileManager()

    # Assume you have an execution ID from a previous run
    execution_id = "exec-2024-001"

    # Get all files from this run
    files = fm.get_run_files(execution_id)

    print(f"\nFound {len(files)} files from execution {execution_id}:")
    for file in files:
        print(f"  - {file['name']}: {file['size']} bytes ({file['category']})")
        print(f"    Content-Type: {file['content_type']}")
        print(f"    Created: {file['date_created']}")
        print()


def example_2_export_file():
    """Export a file from a run to the filesystem."""
    print("=" * 60)
    print("Example 2: Export a file from a run")
    print("=" * 60)

    fm = FileManager()

    execution_id = "exec-2024-001"
    file_name = "output.dat"
    output_path = "/tmp/exported_output.dat"

    success = fm.export_run_file(execution_id, file_name, output_path)

    if success:
        print(f"\n✓ Successfully exported {file_name} to {output_path}")
    else:
        print(f"\n✗ Failed to export {file_name}")


def example_3_simulation_files():
    """Get all files for a simulation across all runs."""
    print("=" * 60)
    print("Example 3: Get all files for a simulation")
    print("=" * 60)

    # For this to work, you need the catalog service running
    session = get_session_manager().create_anonymous_session()
    fm = FileManager(
        cache_url="http://localhost:8001",
        session_id=session.session_id
    )

    simulation_name = "thermal_sim"
    simulation_version = "1.0.0"

    files = fm.get_simulation_files(simulation_name, simulation_version)

    print(f"\nFound {len(files)} files for {simulation_name} v{simulation_version}:")
    for file in files:
        print(f"  - {file['execution_id']}: {file['name']} ({file['size']} bytes)")


def example_4_organize_files():
    """Organize files in folders using FileManager."""
    print("=" * 60)
    print("Example 4: Organize files in folders")
    print("=" * 60)

    fm = FileManager()

    # Create a folder for simulation outputs
    folder = fm.create_folder(
        name="thermal_sim_outputs",
        creator="user123"
    )
    print(f"\nCreated folder: {folder['name']} (ID: {folder['id']})")

    # Create a file entry (representing a sim2l output)
    file = fm.create_file(
        name="temperature_profile.csv",
        size=2048,
        uri="/data/runs/exec-001/temperature_profile.csv",
        creator="user123",
        parent_id=folder['id'],
        metadata={
            'simulation': 'thermal_sim',
            'version': '1.0.0',
            'execution_id': 'exec-001'
        }
    )
    print(f"Created file: {file['name']} in folder {folder['name']}")

    # List folder contents
    contents = fm.list_folder(folder['id'])
    print(f"\nFolder contents ({len(contents)} items):")
    for item in contents:
        print(f"  - {item['name']}")


def example_5_run_database_direct():
    """Direct access to run database artifacts."""
    print("=" * 60)
    print("Example 5: Direct access to run database")
    print("=" * 60)

    # This shows how files are stored in the run database
    execution_id = "exec-2024-001"

    try:
        run_db = RunDatabase(execution_id)

        # Get run summary
        summary = run_db.get_summary()
        print(f"\nRun Summary:")
        print(f"  Simulation: {summary['simulation_name']} v{summary['simulation_version']}")
        print(f"  Status: {summary['status']}")
        print(f"  Duration: {summary['duration_seconds']}s")

        # Get all artifacts (files)
        artifacts = run_db.get_artifacts()
        print(f"\nArtifacts ({len(artifacts)} files):")
        for artifact in artifacts:
            print(f"  - {artifact['name']}")
            print(f"    Category: {artifact['category']}")
            print(f"    Size: {len(artifact.get('content', b''))} bytes")
            print(f"    Path: {artifact.get('path', 'N/A')}")

    except Exception as e:
        print(f"\n✗ Error accessing run database: {e}")


def example_6_batch_export():
    """Export all files from a run to a directory."""
    print("=" * 60)
    print("Example 6: Batch export all run files")
    print("=" * 60)

    import os

    fm = FileManager()
    execution_id = "exec-2024-001"
    output_dir = "/tmp/sim2l_exports"

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Get all files
    files = fm.get_run_files(execution_id)

    print(f"\nExporting {len(files)} files to {output_dir}...")

    success_count = 0
    for file in files:
        output_path = os.path.join(output_dir, file['name'])
        if fm.export_run_file(execution_id, file['name'], output_path):
            print(f"  ✓ {file['name']}")
            success_count += 1
        else:
            print(f"  ✗ {file['name']} (failed)")

    print(f"\nExported {success_count}/{len(files)} files successfully")


def example_7_workflow():
    """Complete workflow: run simulation, get files, export."""
    print("=" * 60)
    print("Example 7: Complete workflow")
    print("=" * 60)

    # Step 1: Assume you just ran a simulation
    # (In real code, this would be: result = sim.run(...))
    execution_id = "exec-2024-001"
    print(f"\n1. Simulation completed with execution_id: {execution_id}")

    # Step 2: Initialize FileManager
    fm = FileManager()
    print("2. FileManager initialized")

    # Step 3: Get all generated files
    files = fm.get_run_files(execution_id)
    print(f"3. Found {len(files)} output files")

    # Step 4: Filter for specific file types
    csv_files = [f for f in files if f['name'].endswith('.csv')]
    print(f"4. Found {len(csv_files)} CSV files")

    # Step 5: Export CSV files
    import os
    export_dir = "/tmp/sim2l_csv_exports"
    os.makedirs(export_dir, exist_ok=True)

    for csv_file in csv_files:
        output_path = os.path.join(export_dir, csv_file['name'])
        fm.export_run_file(execution_id, csv_file['name'], output_path)

    print(f"5. Exported CSV files to {export_dir}")

    # Step 6: Create organized folder structure
    folder = fm.create_folder(
        name=f"run_{execution_id}",
        creator="system",
        metadata={'execution_id': execution_id}
    )
    print(f"6. Created folder: {folder['name']}")

    # Step 7: Register files in folder
    for file in files:
        fm.create_file(
            name=file['name'],
            size=file['size'],
            uri=file['uri'],
            creator="system",
            parent_id=folder['id'],
            metadata={
                'execution_id': execution_id,
                'category': file['category'],
                'content_type': file['content_type']
            }
        )
    print(f"7. Registered {len(files)} files in folder")

    print("\n✓ Workflow complete!")


if __name__ == '__main__':
    print("\nSim2l FileManager Examples")
    print("=" * 60)
    print()

    # Run examples
    # Note: Some examples require actual run data to exist

    try:
        example_1_get_run_files()
    except Exception as e:
        print(f"Example 1 failed: {e}\n")

    try:
        example_2_export_file()
    except Exception as e:
        print(f"Example 2 failed: {e}\n")

    # This requires cache service running
    # try:
    #     example_3_simulation_files()
    # except Exception as e:
    #     print(f"Example 3 failed: {e}\n")

    try:
        example_4_organize_files()
    except Exception as e:
        print(f"Example 4 failed: {e}\n")

    try:
        example_5_run_database_direct()
    except Exception as e:
        print(f"Example 5 failed: {e}\n")

    try:
        example_6_batch_export()
    except Exception as e:
        print(f"Example 6 failed: {e}\n")

    try:
        example_7_workflow()
    except Exception as e:
        print(f"Example 7 failed: {e}\n")

    print("\n" + "=" * 60)
    print("Examples complete!")
    print("=" * 60)
